### ISSUE TITLE
hang when creating a component from blank

### ISSUE THREAD

**Issue by eivinh** [flathub/co.luoja.Telyn#1]
Telyn v1.0.3 (flatpak) hangs when I do the following:

1. Create a new Pattern
2. Create a new Component from blank

I have tried this out on Fedora Silverblue 35, Fedora Workstation 35 and Ubuntu 21.10, the same behaviour on all of them.
The output on command line is a bit sparse, but here it is in case it helps:
```
Attempting to create component editor scene
[TelynGtk.GtkNavigator.Record.controller(TelynGtk.Weak<GtkKit.WidgetController>, viewModel: TelynGtk.Weak<TelynViewModel.ViewModel>, presenter: TelynGtk.GtkNavigator.Presenter.root)]
[TelynGtk.GtkNavigator.Record.controller(TelynGtk.Weak<GtkKit.WidgetController>, viewModel: TelynGtk.Weak<TelynViewModel.ViewModel>, presenter: TelynGtk.GtkNavigator.Presenter.root)]

(TelynGtk:2): GLib-GObject-WARNING **: 17:09:05.276: value "0.250000" of type 'gdouble' is invalid or out of range for property 'delay-factor' of type 'gdouble'
5.0

```

**Comment by Kiwijane3** [comment]
Thank you for reporting this bug. I've written a fix for it, and will push an update on monday.

**Comment by Kiwijane3** [comment]
Sorry, it is quite stupid of me to release something with such a serious bug and take so long to realise. My most sincere apologies. I have pushed a commit that references a build that fixes this bug and has some other improvements.

**Comment by Kiwijane3** [comment]
The new version with the bug fix has been published, so I'm closing this issue.
